fixtures:
  repositories:
    puppi:   "https://github.com/example42/puppi.git"
    stdlib:  "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    yum:     "https://github.com/Nekroze/puppet-yum.git"
    archive: "https://github.com/gini/puppet-archive.git"
  symlinks:
    ganeti: "#{source_dir}"
