fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    yum:    "https://github.com/example42/puppet-yum.git"
    puppi:  "https://github.com/example42/puppi.git"
  symlinks:
    ganeti: "#{source_dir}"
