name          'nekroze-ganeti'
version       '0.1.0'
source        'https://github.com/Nekroze/puppet-ganeti.git'
author        'Taylor "Nekroze" Lawson'
license       'MIT'
summary       'Ganeti Hypervisor Management'
description   ''
project_page  'https://github.com/Nekroze/puppet-ganeti'

dependency 'puppetlabs/stdlib', '>=4.4.0'
dependency 'example42/yum', '>=2.1.17'
dependency 'gini/archive', '>=0.2.1'
dependency 'stankevich/python', '>=1.7.16'