name          'nekroze-ganeti'
version       '0.1.0'
source        'https://github.com/Nekroze/puppet-ganeti.git'
author        'Taylor "Nekroze" Lawson'
license       'MIT'
summary       'Ganeti Hypervisor Management'
description   ''
project_page  'https://github.com/Nekroze/puppet-ganeti'

dependency 'puppetlabs/stdlib'
